### ISSUE TITLE
JabRef 4.0beta3 hangs on startup

### ISSUE THREAD

**Issue by ulfjack** [JabRef/jabref#3207]
```
$ java -jar java/app/JabRef-4.0-beta3.jar 
22:26:11.835 [AWT-EventQueue-0] INFO  org.jabref.logic.importer.OpenDatabase - Opening: /Users/ulfjack/Projects/research/papers/bibliography/floating-point.bib
22:26:12.328 [AWT-EventQueue-0] ERROR org.jabref.FallbackExceptionHandler - Uncaught exception Occurred in Thread[AWT-EventQueue-0,6,main]
java.lang.IllegalAccessError: tried to access method com.sun.javafx.css.parser.CSSParser.<init>()V from class de.jensd.fx.glyphs.GlyphIcon
	at de.jensd.fx.glyphs.GlyphIcon.<clinit>(GlyphIcon.java:48) ~[JabRef-4.0-beta3.jar:?]
	at org.jabref.gui.IconTheme$JabRefIcon.getGraphicNode(IconTheme.java:308) ~[JabRef-4.0-beta3.jar:?]
	at org.jabref.gui.search.SearchTextField.create(SearchTextField.java:16) ~[JabRef-4.0-beta3.jar:?]
	at org.jabref.gui.search.GlobalSearchBar.<init>(GlobalSearchBar.java:68) ~[JabRef-4.0-beta3.jar:?]
	at org.jabref.gui.JabRefFrame.<init>(JabRefFrame.java:168) ~[JabRef-4.0-beta3.jar:?]
	at org.jabref.JabRefGUI.openWindow(JabRefGUI.java:100) ~[JabRef-4.0-beta3.jar:?]
	at org.jabref.JabRefGUI.<init>(JabRefGUI.java:63) ~[JabRef-4.0-beta3.jar:?]
	at org.jabref.JabRefMain.lambda$start$1(JabRefMain.java:145) ~[JabRef-4.0-beta3.jar:?]
	at org.jabref.JabRefMain$$Lambda$78/1737851061.run(Unknown Source) ~[?:?]
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311) ~[?:1.8.0_25]
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:744) ~[?:1.8.0_25]
	at java.awt.EventQueue.access$400(EventQueue.java:97) ~[?:1.8.0_25]
	at java.awt.EventQueue$3.run(EventQueue.java:697) ~[?:1.8.0_25]
	at java.awt.EventQueue$3.run(EventQueue.java:691) ~[?:1.8.0_25]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_25]
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75) ~[?:1.8.0_25]
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:714) ~[?:1.8.0_25]
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201) [?:1.8.0_25]
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116) [?:1.8.0_25]
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105) [?:1.8.0_25]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101) [?:1.8.0_25]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93) [?:1.8.0_25]
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82) [?:1.8.0_25]
```

**Comment by ulfjack** [comment]
My version of Java:
```
$ java -version
java version "1.8.0_25"
Java(TM) SE Runtime Environment (build 1.8.0_25-b17)
Java HotSpot(TM) 64-Bit Server VM (build 25.25-b02, mixed mode)
```

**Comment by ulfjack** [comment]
Oh, yeah, this is on MacOS 10.12.5.

**Comment by ulfjack** [comment]
Grepcode says that the constructor is private - http://grepcode.com/file/repo1.maven.org/maven2/net.java.openjfx.backport/openjfx-78-backport/1.8.0-ea-b96.1/com/sun/javafx/css/parser/CSSParser.java

**Comment by matthiasgeiger** [comment]
Could you please Update your Java version. There were some important changes regarding JavaFX in one of the minor updates (I think it was 1.8.0_60).

Thanks!

**Comment by ulfjack** [comment]
Seems to work with 1.8.0_144. Thanks. Consider having a check at startup and give an error message instead of failing silently?

**Comment by bsreram85** [comment]
Can it be run on Java 9 ? I get a similar exception with Java 9.

14:19:33.478 [AWT-EventQueue-0] ERROR org.jabref.FallbackExceptionHandler - Uncaught exception occurred in Thread[AWT-EventQueue-0,6,main]
java.lang.NoClassDefFoundError: com/sun/javafx/css/parser/CSSParser
        at de.jensd.fx.glyphs.GlyphIcon.<clinit>(GlyphIcon.java:48) ~[JabRef-4.0.jar:?]
        at org.jabref.gui.IconTheme$JabRefIcon.getGraphicNode(IconTheme.java:308) ~[JabRef-4.0.jar:?]
        at org.jabref.gui.search.SearchTextField.create(SearchTextField.java:16) ~[JabRef-4.0.jar:?]
        at org.jabref.gui.search.GlobalSearchBar.<init>(GlobalSearchBar.java:70) ~[JabRef-4.0.jar:?]
        at org.jabref.gui.JabRefFrame.<init>(JabRefFrame.java:168) ~[JabRef-4.0.jar:?]
        at org.jabref.JabRefGUI.openWindow(JabRefGUI.java:100) ~[JabRef-4.0.jar:?]
        at org.jabref.JabRefGUI.<init>(JabRefGUI.java:63) ~[JabRef-4.0.jar:?]
        at org.jabref.JabRefMain.lambda$start$1(JabRefMain.java:146) ~[JabRef-4.0.jar:?]
        at java.awt.event.InvocationEvent.dispatch(Unknown Source) ~[?:?]
        at java.awt.EventQueue.dispatchEventImpl(Unknown Source) ~[?:?]
        at java.awt.EventQueue.access$500(Unknown Source) ~[?:?]
        at java.awt.EventQueue$3.run(Unknown Source) ~[?:?]
        at java.awt.EventQueue$3.run(Unknown Source) ~[?:?]
        at java.security.AccessController.doPrivileged(Native Method) ~[?:?]
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source) ~[?:?]
        at java.awt.EventQueue.dispatchEvent(Unknown Source) ~[?:?]
        at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source) [?:?]
        at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source) [?:?]
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source) [?:?]
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source) [?:?]
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source) [?:?]
        at java.awt.EventDispatchThread.run(Unknown Source) [?:?]
Caused by: java.lang.ClassNotFoundException: com.sun.javafx.css.parser.CSSParser
        at jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source) ~[?:?]
        at jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(Unknown Source) ~[?:?]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
        ... 22 more

**Comment by bsreram85** [comment]
By the way i use JabRef 4.0. Having problems to start JabRef with Java 9. Should i downgrade to Java 8 ? :-(

**Comment by matthiasgeiger** [comment]
Yes. Currently it is not possible to run JabRef 4.0 (and the current dev builds) using Java 9 due to some incompatible libraries... 😥
