### ISSUE TITLE
Saving on network drives does not finish

### ISSUE THREAD

**Issue by chrik5** [JabRef/jabref#3672]
Hello,
 
Thanks for the nice bibligraphy manager, which I'm using since 2005. 
Unfortunately, saving on network drives stopped working for me. So I tried the latest snapshot, but without luck:
JabRef version JabRef-4.2-dev--snapshot--2018-01-28--master--cfb424f80 on Windows 10

Steps to reproduce:

1. open bibliography file from network drive
2. change something in the bibliography 
3. save changes 
4. saving never finishes, but the bibliography file got saved
5. I need to kill jabref from the task manager

This is the log output once save is pressed:
<details>
09:14:18.938 [AWT-EventQueue-0] ERROR org.jabref.gui.BasePanel - runCommand error: null
java.lang.NullPointerException: null
        at java.nio.file.Files.provider(Unknown Source) ~[?:1.8.0_161]
        at java.nio.file.Files.exists(Unknown Source) ~[?:1.8.0_161]
        at org.jabref.logic.util.io.FileUtil.copyFile(FileUtil.java:161) ~[JabRef-4.2-dev--snapshot--2018-01-28--master--cfb424f80.jar:?]
        at org.jabref.gui.collab.DatabaseChangeMonitor.copyToTemp(DatabaseChangeMonitor.java:156) ~[JabRef-4.2-dev--snapshot--2018-01-28--master--cfb424f80.jar:?]
        at org.jabref.gui.collab.DatabaseChangeMonitor.lambda$markAsSaved$3(DatabaseChangeMonitor.java:148) ~[JabRef-4.2-dev--snapshot--2018-01-28--master--cfb424f80.jar:?]
        at java.util.Optional.ifPresent(Unknown Source) ~[?:1.8.0_161]
        at org.jabref.gui.collab.DatabaseChangeMonitor.markAsSaved(DatabaseChangeMonitor.java:143) ~[JabRef-4.2-dev--snapshot--2018-01-28--master--cfb424f80.jar:?]
        at org.jabref.gui.collab.DatabaseChangeMonitor.markExternalChangesAsResolved(DatabaseChangeMonitor.java:139) ~[JabRef-4.2-dev--snapshot--2018-01-28--master--cfb424f80.jar:?]
        at java.util.Optional.ifPresent(Unknown Source) ~[?:1.8.0_161]
        at org.jabref.gui.BasePanel.markExternalChangesAsResolved(BasePanel.java:1826) ~[JabRef-4.2-dev--snapshot--2018-01-28--master--cfb424f80.jar:?]
        at org.jabref.gui.exporter.SaveDatabaseAction.checkExternalModification(SaveDatabaseAction.java:448) ~[JabRef-4.2-dev--snapshot--2018-01-28--master--cfb424f80.jar:?]
        at org.jabref.gui.exporter.SaveDatabaseAction.init(SaveDatabaseAction.java:89) ~[JabRef-4.2-dev--snapshot--2018-01-28--master--cfb424f80.jar:?]
        at org.jabref.gui.BasePanel.runWorker(BasePanel.java:293) ~[JabRef-4.2-dev--snapshot--2018-01-28--master--cfb424f80.jar:?]
        at org.jabref.gui.BasePanel.runCommand(BasePanel.java:1078) [JabRef-4.2-dev--snapshot--2018-01-28--master--cfb424f80.jar:?]
        at org.jabref.gui.JabRefFrame$GeneralAction.actionPerformed(JabRefFrame.java:2054) [JabRef-4.2-dev--snapshot--2018-01-28--master--cfb424f80.jar:?]
        at javax.swing.AbstractButton.fireActionPerformed(Unknown Source) [?:1.8.0_161]
        at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source) [?:1.8.0_161]
        at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source) [?:1.8.0_161]
        at javax.swing.DefaultButtonModel.setPressed(Unknown Source) [?:1.8.0_161]
        at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source) [?:1.8.0_161]
        at java.awt.AWTEventMulticaster.mouseReleased(Unknown Source) [?:1.8.0_161]
        at java.awt.Component.processMouseEvent(Unknown Source) [?:1.8.0_161]
        at javax.swing.JComponent.processMouseEvent(Unknown Source) [?:1.8.0_161]
        at java.awt.Component.processEvent(Unknown Source) [?:1.8.0_161]
        at java.awt.Container.processEvent(Unknown Source) [?:1.8.0_161]
        at java.awt.Component.dispatchEventImpl(Unknown Source) [?:1.8.0_161]
        at java.awt.Container.dispatchEventImpl(Unknown Source) [?:1.8.0_161]
        at java.awt.Component.dispatchEvent(Unknown Source) [?:1.8.0_161]
        at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source) [?:1.8.0_161]
        at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source) [?:1.8.0_161]
        at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source) [?:1.8.0_161]
        at java.awt.Container.dispatchEventImpl(Unknown Source) [?:1.8.0_161]
        at java.awt.Window.dispatchEventImpl(Unknown Source) [?:1.8.0_161]
        at java.awt.Component.dispatchEvent(Unknown Source) [?:1.8.0_161]
        at java.awt.EventQueue.dispatchEventImpl(Unknown Source) [?:1.8.0_161]
        at java.awt.EventQueue.access$500(Unknown Source) [?:1.8.0_161]
        at java.awt.EventQueue$3.run(Unknown Source) [?:1.8.0_161]
        at java.awt.EventQueue$3.run(Unknown Source) [?:1.8.0_161]
        at java.security.AccessController.doPrivileged(Native Method) [?:1.8.0_161]
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source) [?:1.8.0_161]
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source) [?:1.8.0_161]
        at java.awt.EventQueue$4.run(Unknown Source) [?:1.8.0_161]
        at java.awt.EventQueue$4.run(Unknown Source) [?:1.8.0_161]
        at java.security.AccessController.doPrivileged(Native Method) [?:1.8.0_161]
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source) [?:1.8.0_161]
        at java.awt.EventQueue.dispatchEvent(Unknown Source) [?:1.8.0_161]
        at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source) [?:1.8.0_161]
        at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source) [?:1.8.0_161]
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source) [?:1.8.0_161]
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source) [?:1.8.0_161]
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source) [?:1.8.0_161]
        at java.awt.EventDispatchThread.run(Unknown Source) [?:1.8.0_161]
</details>

Ciao,
Christian

**Comment by Siedlerchr** [comment]
Hi,
I could not reproduce this on my Win10 machine, so I need some more details.
I tried both opening and saving from an UNC path eg. \\xxxx\_jabreftemp\bib.bib and mounting the folder as drive Z.
How does your network drive config look like?
Is this error reproducible or did it occur only once?

**Comment by chrik5** [comment]
Hi,

Sorry for the late reply. I was out of office.
It happens for me every time and I need to kill jabref every time. I tried it with a mounted CIFS from a samba Server and on a Novell/OES drive. It happens for example with the attached file.
 
[test2.zip](https://github.com/JabRef/jabref/files/1719602/test2.zip)

Thanks,
Christian

**Comment by koppor** [comment]
May I ask at which JabRef version it stopped working? 3.0? 4.1? That would maybe help us to reproduce the issue.

**Comment by chrik5** [comment]
Now, I tested the jar releases from 3.8.2 onwards and until version 4.0 everthing works fine. 

With 4.1 I run into this issue. 


Invoking jabref from the cmd.exe with: `java -jar JabRef-4.1.jar`

shows this in the cmd.exe

AI: INFO 23-02-2018 17:53, 22: Configuration file has been successfully found as resource
17:53:56.043 [AWT-EventQueue-0] INFO  org.jabref.logic.importer.OpenDatabase - Opening: N:\H915\tmp\test_382.bib
File: grouptree.fxml not found, attempting with camel case
File: grouptree.css not found, attempting with camel case
17:53:57.864 [AWT-EventQueue-0] ERROR org.jabref.gui.collab.DatabaseChangeMonitor - Error while trying to monitor N:\H915\tmp\test_382.bib
java.io.IOException: Unzulõssige Funktion.

        at sun.nio.fs.WindowsWatchService$Poller.implRegister(Unknown Source) ~[?:1.8.0_161]
        at sun.nio.fs.AbstractPoller.processRequests(Unknown Source) ~[?:1.8.0_161]
        at sun.nio.fs.WindowsWatchService$Poller.run(Unknown Source) ~[?:1.8.0_161]
        at java.lang.Thread.run(Unknown Source) ~[?:1.8.0_161]

Pressing the save button produces:
<details>
17:55:00.313 [JabRef CachedThreadPool] ERROR org.jabref.JabRefExecutorService - Problem executing command
java.util.concurrent.ExecutionException: java.lang.NullPointerException
        at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0_161]
        at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0_161]
        at org.jabref.JabRefExecutorService.executeInterruptableTaskAndWait(JabRefExecutorService.java:107) ~[JabRef-4.1.jar:?]
        at org.jabref.gui.exporter.SaveDatabaseAction.lambda$checkExternalModification$4(SaveDatabaseAction.java:427) ~[JabRef-4.1.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_161]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_161]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_161]
Caused by: java.lang.NullPointerException
        at org.jabref.gui.collab.ChangeScanner.run(ChangeScanner.java:126) ~[JabRef-4.1.jar:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_161]
        at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_161]
        ... 3 more
17:55:00.313 [JabRef CachedThreadPool] ERROR org.jabref.JabRefExecutorService - Problem executing command
java.util.concurrent.ExecutionException: java.lang.NullPointerException
        at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0_161]
        at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0_161]
        at org.jabref.JabRefExecutorService.executeInterruptableTaskAndWait(JabRefExecutorService.java:107) ~[JabRef-4.1.jar:?]
        at org.jabref.gui.exporter.SaveDatabaseAction.lambda$checkExternalModification$4(SaveDatabaseAction.java:427) ~[JabRef-4.1.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_161]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_161]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_161]
Caused by: java.lang.NullPointerException
        at org.jabref.gui.collab.ChangeScanner.run(ChangeScanner.java:126) ~[JabRef-4.1.jar:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_161]
        at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_161]
        ... 3 more
17:55:00.314 [JabRef CachedThreadPool] ERROR org.jabref.JabRefExecutorService - Problem executing command
java.util.concurrent.ExecutionException: java.lang.NullPointerException
        at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0_161]
        at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0_161]
        at org.jabref.JabRefExecutorService.executeInterruptableTaskAndWait(JabRefExecutorService.java:107) ~[JabRef-4.1.jar:?]
        at org.jabref.gui.exporter.SaveDatabaseAction.lambda$checkExternalModification$4(SaveDatabaseAction.java:427) ~[JabRef-4.1.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_161]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_161]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_161]
Caused by: java.lang.NullPointerException
        at org.jabref.gui.collab.ChangeScanner.run(ChangeScanner.java:126) ~[JabRef-4.1.jar:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_161]
        at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_161]
        ... 3 more
</details>

**Comment by koppor** [comment]
@chrik5 Do you have a JDK running? May I ask whether you could invest some more time?

1. Checkout JabRef
2. run `git checkout v4.0`
3. run `git bisect start`
4. run `git bisect good`
5. run `git checkout v4.1`
6. run `git bisect bad`
7. Wait for git checkout out another version
8. run `./gradlew run` and test.
9. Type in either `git bisect good` or `git bisect bad` depending on whether it is good or bad
10. go to 7.

I know, this costs much time, but this really, really, helps us in tracking down the issue.

**Comment by chrik5** [comment]
@koppor No I do not have JDK running and no programming skills. Anyway, I installed JDK 9.0.4 and got until point 8. 

`D:\jabref\jabref>gradlew run`

fails with build error

```
> Task :compileJava
Processing annotations
Annotations processed
Processing annotations
No elements to process
D:\jabref\jabref\src\main\java\org\jabref\gui\fieldeditors\EditorTextArea.java:14: error: cannot find symbol
import com.sun.javafx.scene.control.skin.TextAreaSkin;
                                        ^
  symbol:   class TextAreaSkin
  location: package com.sun.javafx.scene.control.skin
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
1 error
```

I will look into this after the weekend.

**Comment by koppor** [comment]
thank you for your parience. You need JDK8 🙈.

**Comment by koppor** [comment]
And a openjdk javafx package (in the case of Linux)

**Comment by tobiasdiez** [comment]
The NPE points to L126
https://github.com/JabRef/jabref/blob/4ddd90a6727ed1d2b1ee2d79faf313a876de9be4/src/main/java/org/jabref/gui/collab/ChangeScanner.java#L125-L127
thus I would suspect that `tempFile` is null, which happens because JabRef is for some reason not able to create the temp file on the external network drive.

**Comment by chrik5** [comment]
I can not get a build of jabref. Another windows 10 install, fresh java 8 JDK no luck with building jabref as well. But here I do not have any issue with saving. 

On a 3rd windows install I have the issue, but I do not know what the difference might be. BTW. where are the configs stored for the preferences?

```
C:\Users\kanzian\jabref\src\main\java\org\jabref\logic\util\io\FileUtil.java:339: error: [StreamResourceLeak] Streams that encapsulate a closeable resource should be closed using try-with-resources
            return Files.walk(rootDirectory)
                             ^
    (see http://errorprone.info/bugpattern/StreamResourceLeak)
  Did you mean 'try (Stream<Path> stream = Files.walk(rootDirectory)) {'?
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
```

**Comment by Siedlerchr** [comment]
@chrik5 Hi, you ran into a nasty issue we fixed a couple of days laster. You need to checkout at least commit: d0f62702bbed02e8bf4e99f428f4fe75dfaaf021

**Comment by chrik5** [comment]
@Siedlerchr Yes the postet commit compiles, but this means I can't bisect from v4.0 to v4.1. Unless I know howto patch v4.0 I guess?

**Comment by Siedlerchr** [comment]
@chrik5  Um, that's particularly bad in this situation. The only solution I see is to cherry pick the specific commit (every time) 
`git cherry-pick d0f6270`
 and then starting the bisect again.  I am not that into the internals of git. Maybe @koppor  has an idea 

Preferences are stored in the registry. 
You can reset them using  the commandline switch `-d all` or manually in the settings window.

**Comment by tobiasdiez** [comment]
Thanks @chrik5 for your assistance and your willingness to run `git bisect`. However, in this particular case, I think it is easier if one of the developer traces back how `tempFile` in 
https://github.com/JabRef/jabref/blob/4ddd90a6727ed1d2b1ee2d79faf313a876de9be4/src/main/java/org/jabref/gui/collab/ChangeScanner.java#L125-L127
can be null instead of running the bisect.

**Comment by Siedlerchr** [comment]
I think your problem is the same as described here, https://github.com/dotnet/corefx/issues/7576 
I am not an export, but when I understand that post right, it's more or less a windows problem with network shares which are not NTFS. 

While this is .NET, the underlying Windows API function is https://msdn.microsoft.com/en-us/library/windows/desktop/aa365465(v=vs.85).aspx
is also used by JAVA. 
http://hg.openjdk.java.net/jdk8/jdk8/jdk/file/tip/src/windows/classes/sun/nio/fs/WindowsWatchService.java

**Comment by tobiasdiez** [comment]
This should be fixed in the latest development version. Could you please check the build from http://builds.jabref.org/master/. Thanks! Please remember to make a backup of your library before trying-out this version.
