### PR TITLE
Add doi-to-bibtex to examples and JabKit

### PR DESCRIPTION
**Pull request by koppor**
Strongly demanded by the community. Was available inside JabRef; now we can offer as CLI.

Kind of follow-up to https://github.com/JabRef/jabref/pull/14233.

We use [CrossRef](https://www.crossref.org/)

### Steps to test

Create and modify debug configuration for `org.jabref.JabKit#main`

image

### Mandatory checks

- [x] I own the copyright of the code submitted and I license it under the [MIT license](https://github.com/JabRef/jabref/blob/main/LICENSE)
- [x] I manually tested my changes in running JabRef (always required)
- [/] I added JUnit tests for changes (if applicable)
- [/] I added screenshots in the PR description (if change is visible to the user)
- [x] I described the change in `CHANGELOG.md` in a way that is understandable for the average user (if change is visible to the user)
- [/] I checked the [user documentation](https://docs.jabref.org/): Is the information available and up to date? If not, I created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, I submitted a pull request updating file(s) in <https://github.com/JabRef/user-documentation/tree/main/en>.

### CODE REVIEW

**Comment by palukku** [comment]
I tried running it with a valid and an completely invalid doi `1234test` as two arguments and it threw an error:
```bash
Unmatched argument at index 2: '1abref'
Usage: jabkit doi-to-bibtex DOI...
Converts a DOI to BibTeX
      DOI...   one or more DOIs to fetch
```

But I would say it should not completely "crash" but print out the valid one and for the second the `Could not fetch DOI from BibTeX`.

File: jabkit/src/main/java/org/jabref/cli/DoiToBibtex.java [hunk 1]
```diff
@@ -0,0 +1,68 @@
...
+
+    @CommandLine.ParentCommand
+    private ArgumentProcessor argumentProcessor;
+
+    @Parameters(paramLabel = "DOI", description = "one or more DOIs to fetch", arity = "1..*")
+    private DOI[] dois;
+
+    @Override
+    public Integer call() {
+        var fetcher = new CrossRef();
```
Comment (subhramit) [inline jabkit/src/main/java/org/jabref/cli/DoiToBibtex.java]:
```suggestion
        CrossRef fetcher = new CrossRef();
```

File: jabkit/src/main/java/org/jabref/cli/DoiToBibtex.java [hunk 2]
```diff
@@ -0,0 +1,68 @@
...
+                LOGGER.error("Could not fetch DOI from BibTeX");
+                continue;
+            }
+
+            entries.add(entry.get());
+        }
+
+        try (var writer = new OutputStreamWriter(System.out, StandardCharsets.UTF_8)) {
+            var context = new BibDatabaseContext(new BibDatabase(entries));
+            var bibWriter = new BibDatabaseWriter(writer, context, argumentProcessor.cliPreferences);
```
Comment (subhramit) [inline jabkit/src/main/java/org/jabref/cli/DoiToBibtex.java]:
```suggestion
       try (OutputStreamWriter writer = new OutputStreamWriter(System.out, StandardCharsets.UTF_8)) {
            BibDatabaseContext context = new BibDatabaseContext(new BibDatabase(entries));
            BibDatabaseWriter bibWriter = new BibDatabaseWriter(writer, context, argumentProcessor.cliPreferences);
```

**Comment by palukku** [comment]
And maybe also a option which disables the error messages but still returns exit code 1, so if you want to work with the output and ignore errors for example. Can't name a case for that, but i can imagine that it could be helpful. 

But one could probably just read the out and ignore err output and achieve it without the extra option

**Comment by koppor** [comment]
> Micro comments - I am committed to not letting vars enter again - so keeping them only in the example file

We should create an architecture test for that ^^

**Comment by koppor** [comment]
It's far from perfect... Even with `--porcelain` we get some error output.

Needs to be more thought how we deal with `--porcelain`

I tried with

    doi-to-bibtex --porcelain abc 10:333 10.47397/tb/44-3/tb138kopp-jabref

Result:

```
2025-11-09 16:12:37 [main] org.jabref.logic.preferences.JabRefCliPreferences.getFetcherKeysFromKeyring()
WARN: JabRef could not open the key store
2025-11-09 16:12:39 [main] org.jabref.logic.journals.JournalAbbreviationLoader.loadRepository()
INFO: Loaded journal abbreviations from C:\Users\olive\AppData\Local\Temp\jabref-journal831676151345966999\journal-list.mv
2025-11-09 16:12:39 [main] org.jabref.cli.DoiToBibtex.call()
WARN: Skipped DOI abc, because it is not a valid DOI string
2025-11-09 16:12:40 [main] org.jabref.logic.net.URLDownload.openConnection()
INFO: https://api.crossref.org/works/10:333: SimpleHttpResponse{statusCode=404, responseMessage='Not Found', responseBody='Resource not found.'}
2025-11-09 16:12:40 [main] org.jabref.cli.DoiToBibtex.call()
ERROR: Could not fetch DOI from BibTeX: org.jabref.logic.importer.FetcherClientException: 
	at org.jabref.jablib/org.jabref.logic.net.URLDownload.openConnection(URLDownload.java:389)
	at org.jabref.jablib/org.jabref.logic.net.URLDownload.asInputStream(URLDownload.java:279)
	at org.jabref.jablib/org.jabref.logic.importer.IdBasedParserFetcher.performSearchById(IdBasedParserFetcher.java:50)
	at org.jabref.jabkit/org.jabref.cli.DoiToBibtex.call(DoiToBibtex.java:49)
	at org.jabref.jabkit/org.jabref.cli.DoiToBibtex.call(DoiToBibtex.java:25)
	at info.picocli@4.7.7/picocli.CommandLine.executeUserObject(CommandLine.java:2031)
	at info.picocli@4.7.7/picocli.CommandLine.access$1500(CommandLine.java:148)
	at info.picocli@4.7.7/picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2469)
	at info.picocli@4.7.7/picocli.CommandLine$RunLast.handle(CommandLine.java:2461)
	at info.picocli@4.7.7/picocli.CommandLine$RunLast.handle(CommandLine.java:2423)
	at info.picocli@4.7.7/picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2277)
	at info.picocli@4.7.7/picocli.CommandLine$RunLast.execute(CommandLine.java:2425)
	at info.picocli@4.7.7/picocli.CommandLine.execute(CommandLine.java:2174)
	at org.jabref.jabkit/org.jabref.JabKit.main(JabKit.java:99)
ERROR: Could not fetch DOI from BibTeX: org.jabref.logic.importer.FetcherClientException: 

@Article{,
  author    = {Oliver Kopp and Carl Christian Snethlage and Christoph Schwentker},
  title     = {JabRef: BibTeX-based literature management software},
  doi       = {10.47397/tb/44-3/tb138kopp-jabref},
  issn      = {0896-3207},
  number    = {3},
  pages     = {441-447},
  volume    = {44},
  journal   = {TUGboat},
  publisher = {TeX Users Group},
  year      = {2023},
}
```

**Comment by koppor** [comment]
> And maybe also a option which disables the error messages but still returns exit code 1, so if you want to work with the output and ignore errors for example. Can't name a case for that, but i can imagine that it could be helpful.

This is what `--porcelain` is useful for.

> But one could probably just read the out and ignore err output and achieve it without the extra option

This is the intention of this PR ^^

File: CHANGELOG.md [hunk 3]
```diff
@@ -18,6 +18,7 @@ Note that this project **does not** adhere to [Semantic Versioning](https://semv
 ### Changed
 
 - Changed: <kbd>Ctrl</kbd> + <kbd>Shift</kbd> + <kbd>L</kbd> now opens the terminal in the active library directory (#14130)
+- `JabKit`: `--porcelain` does not output any logs to the console any more. [#14244](https://github.com/JabRef/jabref/pull/14244)
```
Comment (subhramit) [inline CHANGELOG.md]:
```suggestion
- `JabKit`: `--porcelain` does not output any logs to the console anymore. [#14244](https://github.com/JabRef/jabref/pull/14244)
```

File: jabkit/src/main/java/org/jabref/cli/DoiToBibtex.java [hunk 4]
```diff
@@ -42,18 +46,21 @@ public Integer call() {
...
-                LOGGER.error("Could not fetch DOI from BibTeX", e);
+                LOGGER.error("Could not fetch BibTeX based on DOI", e);
+                System.err.println(Localization.lang("Error"));
                 continue;
             }
 
             if (entry.isEmpty()) {
-                LOGGER.error("Could not fetch DOI from BibTeX");
+                LOGGER.error("Could not fetch BibTeX based on DOI");
+                System.err.println(Localization.lang("Error"));
```
Comment (subhramit) [inline jabkit/src/main/java/org/jabref/cli/DoiToBibtex.java]: I think the System.err,println messages can be more distinctive - these two cases, for example, both output "Error"

Comment (subhramit) [reply jabkit/src/main/java/org/jabref/cli/DoiToBibtex.java]: In fact the logger messages too - maybe we can make the messages more descriptive saying in one case the entry is empty. May help debugging

Comment (subhramit) [reply jabkit/src/main/java/org/jabref/cli/DoiToBibtex.java]: Weird, this comment is not appearing in my files changed tab

**Comment by koppor** [comment]
OK, `--porcelain` also fixed. Did not want to add new localization, re-used as much as possible.

```
DOI abc is invalid

No data was found for the identifier - 10:333
URL: https://api.crossref.org/works/10:333
HTTP 404 Not Found
Resource not found.

@Article{,
  author    = {Oliver Kopp and Carl Christian Snethlage and Christoph Schwentker},
  title     = {JabRef: BibTeX-based literature management software},
  doi       = {10.47397/tb/44-3/tb138kopp-jabref},
  issn      = {0896-3207},
  number    = {3},
  pages     = {441-447},
  volume    = {44},
  journal   = {TUGboat},
  publisher = {TeX Users Group},
  year      = {2023},
}
```

File: jabkit/src/main/java/org/jabref/cli/DoiToBibtex.java (hunk 4 above)
Comment (koppor) [reply jabkit/src/main/java/org/jabref/cli/DoiToBibtex.java]: I wanted to avoid introducing new localizations.

I found some better strings meanhile at 43b4b87e52

File: jabkit/src/main/java/org/jabref/cli/DoiToBibtex.java [hunk 5]
```diff
@@ -0,0 +1,85 @@
...
+            } catch (FetcherException e) {
+                LOGGER.error("Could not fetch BibTeX based on DOI", e);
+                System.err.println(Localization.lang("No data was found for the identifier" + " - " + doiString));
+                System.err.println(e.getLocalizedMessage());
+                System.err.println();
+                continue;
+            }
+
+            if (entry.isEmpty()) {
+                LOGGER.error("Could not fetch BibTeX based on DOI");
```
Comment (subhramit) [inline jabkit/src/main/java/org/jabref/cli/DoiToBibtex.java]:
```suggestion
                LOGGER.error("Could not fetch BibTeX based on DOI - entry is empty");
```

**Review by subhramit — APPROVED** [review]

**Comment by subhramit** [comment]
ah some ci checks

**Comment by koppor** [comment]
> ah some ci checks

```
 > Compilation failed; see the compiler output below.
  /home/runner/work/jabref/jabref/jabsrv/src/main/java/module-info.java:63: error: module not found: tools.jackson.databind
      requires tools.jackson.databind;
                            ^
```

Refs https://github.com/JabRef/jabref/pull/14259 maybe

**Comment by koppor** [comment]
Somehow jackson was updated in main - and jabsrv does not compile any more.

**Comment by koppor** [comment]
Commit breaking main 32ce0b98cfbdbde2679ef7357ccab4430ab61763
